### ISSUE TITLE
Day 1 Workshop

### ISSUE THREAD

**Issue by sima-qian** [fac-14/OSCEBossKey#24]
![img_9366](https://user-images.githubusercontent.com/29804933/46299261-e1469400-c598-11e8-9425-eb81f0b2161b.JPG)

![img_9367](https://user-images.githubusercontent.com/29804933/46299270-e73c7500-c598-11e8-85f0-ad81aaf3985b.JPG)

**Comment by peterwoodward-court** [comment]
Looks great guys! Here are some example stations:

**Histories**: 
- Headache
- Visual loss
- Cough
- Vomiting
- Shortness of Breath
- Chest Pain
- Abdominal Pain
- Dysuria
- Weakness

**Examinations**:
- Cardiovascular
- Respiratory 
- Abdominal
- Cranial nerves 
- Thyroid
- Upper Limb neurological
- Lower Limb neurological 
- Shoulder
- Hip
- Knee
- Ankle 

And an example mark scheme for a cardiovascular examination which perhaps we can use as a placeholder for now?:

- Wash hands
- Introduction
- Gains consent 
- General inspection 
- Checks peripheral pulses
- Checks blood pressure 
- Inspects JVP
- Palpates carotids 
- Localises apex beat
- Auscultates valve areas with correct positioning 
- Listens to lung bases 
- Checks for ankle oedema 
- Thanks patient & summarises findings
- Washes hands  

Hope that's helpful - let me know if there's anything else you need, thanks for all your hard work so far! :)

**Comment by sima-qian** [comment]
@peterwoodward-court That's great information, thanks. We'll plug it into the prototypes we're preparing for Wednesday.
