### ISSUE TITLE
Do we use passport with our database?

### ISSUE THREAD

**Issue by njons** [fac-14/OSCEBossKey#38]
Martin did a jazzo prezzo on Passport OAuth 

initalise passport
use apssport and set all the strategies
serialise/deserialise user 

create isAuth middleware in controller
each authentication service needs an endpoint

match info with database - unsure how to extrapolate

- handover of info: making a google account for Peter?

**Comment by sima-qian** [comment]
The [`passportjs`](http://www.passportjs.org/) middleware @martingaston found looks promising, in particular the [`passport-oauth2`](http://www.passportjs.org/packages/passport-oauth2/) strategy.
