### ISSUE TITLE
QA time: React components

### ISSUE THREAD

**Issue by njons** [fac-14/OSCEBossKey#52]
Patient details & Mark scheme pages:

- [x] Settle on what should be components
- [x] Writing pseudocode in files to guide development

![img_5768](https://user-images.githubusercontent.com/30963614/46480643-8c4d8c80-c7e9-11e8-8ae7-416b7c6f988a.JPG)

**Comment by martingaston** [comment]
REVISION PAGE
=============

PATIENT INFO
============

<HistoryCaseRevision> - manages state across all child components
        <Header> - container, inherits state and passes props to header components       
                <BackButton> - functional component, uses util method closeCase()
                <StationName> - displays the station name (e.g. 'Chest Pain'), inherits prop stationName (str)
                <TickButton> - displays tick button for submitting mark scheme for evaluation, prop displayed (bool) and submitCase() function.
                <CaseTitle> - dislays the current case title (e.g. '57 year old male started feeling chest pain after drinking milk'
        <Body> - container, inherits state and passes props to body components       
                <SlideBalls> - shows where the user is, animating into a larger ball for their current page. prop position (bool)
                <Article> - displays full article text (e.g. 'John, 57 years old reports that he had chest pain last night...')

MARK SCHEME
===========

<HistoryCaseRevision> *                                      
        <Header> *
                <BackButton> *
                <StationName> *
                <TickButton> *
                <CaseTitle> *
        <Body> *
                <SlideBalls> *
                <MarkList> - iterates through items in the mark scheme with a Map
                        <MarkEntry> - renders an individual item from the mark scheme, props elementText (str) completed (bool)

**Comment by tbtommyb** [comment]
Some thoughts - let me know if this isn't a useful point to share!

What is `HistoryCaseRevision`? Is it the top level global or does it sit under that? I'm not sure if it's referring to a particular revision of a history case or if it's the name of the app if you see what I mean.

Do cases belong to stations? If so, do you think it's worth representing them (stations) in the hierarchy? I'm also wondering if it makes sense to keep all case-level stuff out of the header so that it wouldn't go below the Station level. Then each Station could be responsible for a collection of Cases with titles and content.

**Comment by sima-qian** [comment]
There are essentially two user flows in OSCEBossKey -- the revision flow, and the adding content flow. We're focussing on the revision flow at the moment. Medical students have a few different types of OSCE exams; one type is a `History`. This simulates a patient coming in with a complaint, and the student has to talk to the patient and figure out what's wrong with them or decide which tests they need to run to come to a diagnosis. Students are graded on things like `Washes hands`, `Checks family history`, `Enquires about onset of symptoms`, etc. A specific scenario (e.g. `57-year-old man experiences chest pain after drinking milk`) is called a `Case`.

So, `HistoryRevisionCase` is a React class we're using to contain the page that displays the details of a history case and appropriate mark scheme, which the medical student's revision buddy will refer to and use. This page will be navigated to from a list of cases. Cases belong to a certain `Station`, such as `Chest Pain`, `Headache`, `Visual Loss`. `Stations` are essentially categories of history cases.

I hope that helps explain what's going on -- it took us a little while to get our heads around the exam structure!

**Comment by tbtommyb** [comment]
Cool, that makes much more sense - thanks for the explanation! I see you're going to set up dummy data so I'll take a look at the schema when that's done.
