### ISSUE TITLE
Thursday: Meeting with Peter

### ISSUE THREAD

**Issue by njons** [fac-14/OSCEBossKey#61]
Expecting to be able to go through: 
- [x] Website deployed online 
- [x] Minimal but useful styling 
- [x] Functional **Patient Details** page  (hard coded dummy content only)
- [x] Functional **Mark Scheme** page  (hard coded dummy content only)
- [x] Functional **Case List** page (hard coded dummy content only)
- [x] Functional **Station List** page  (hard coded dummy content only)
- [ ] request content from @peterwoodward-court
- [ ] discuss final wish list with @peterwoodward-court 
- [ ] discuss user testing @peterwoodward-court

**Comment by peterwoodward-court** [comment]
Looking forward to catching up again! I put this in my calendar but haven't put down a time(!) - was there one we spoke about? If not would the afternoon suit, around 15:30?

**Comment by njons** [comment]
Sorry, I missed your message here @peterwoodward-court! As confirmed in the Whatsapp group 3:30 pm works fine for us. We will also have a team discussion today on what exactly we will aim to deliver on Thursday and you'll be able to keep an eye on the list here (I will be checking the boxes as we complete them). Let's refer to this list in our meeting on Thursday.
